./cub3d_debug maps/ko_bonus_door_in_border.cub
./cub3d_debug maps/ko_bonus_wrong_door.cub
./cub3d_debug maps/ko_color_format.cub
./cub3d_debug maps/ko_color_missing.cub
./cub3d_debug maps/ko_color_neg.cub
./cub3d_debug maps/ko_color_over_255.cub
./cub3d_debug maps/ko_color_typo.cub
./cub3d_debug maps/ko_duplicate_info.cub
./cub3d_debug maps/ko_element_order.cub
./cub3d_debug maps/ko_missing_ext
./cub3d_debug maps/ko_missing_space.cub
./cub3d_debug maps/ko_missing_space2.cub
./cub3d_debug maps/ko_missing_wall.cub
./cub3d_debug maps/ko_missing_wall2.cub
./cub3d_debug maps/ko_missing_wall3.cub
./cub3d_debug maps/ko_more_info_than_necessary_info.cub
./cub3d_debug maps/ko_no_player.cub
./cub3d_debug maps/ko_nonsense_map.cub
./cub3d_debug maps/ko_player_in_walls.cub
./cub3d_debug maps/ko_spaces.cub
./cub3d_debug maps/ko_spaces_new_lines.cub
./cub3d_debug maps/ko_spaces_text.cub
./cub3d_debug maps/ko_texture_file_missing.cub
./cub3d_debug maps/ko_texture_missing.cub
./cub3d_debug maps/ko_texture_typo.cub
./cub3d_debug maps/ko_wrong_char.cub
./cub3d_debug maps/ko_wrong_ext.cub1
